baseURL: "http://example.org/"
languageCode: "el"
defaultContentLanguage: "el"
title: "Διαύγεια.org"
theme: "ananke"
enableRobotsTXT: true
copyright: ""

languages:
  en:
    title: "Diavgeia.org"
    languageCode: "en-us"
    contentDir: "content/en"
    params:
      description: "A tech startup NGO for public sector transparency in Greece."
  el:
    title: "Διαύγεια.org"
    languageCode: "el"
    contentDir: "content/el"
    params:
      description: "Μια τεχνολογική μη κερδοσκοπική οργάνωση για τη διεπαφή πολίτη - κράτους"

params:
  background_color_class: "bg-dark-blue"
  custom_css: ["main.css"]
  ananke_socials:
  - name: twitter
    url: https://twitter.com/diavgeia_org
  - name: github
    url: https://github.com/diavgeia-ai